In [1]:
!git clone https://github.com/JiyaSaxena/Entrepreneur-Pitch-Evaluator-Model-

Cloning into 'Entrepreneur-Pitch-Evaluator-Model-'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 48 (delta 12), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (48/48), 15.62 MiB | 8.31 MiB/s, done.
Resolving deltas: 100% (12/12), done.

In [2]:
%cd /content/Entrepreneur-Pitch-Evaluator-Model-
!ls -la

/content/Entrepreneur-Pitch-Evaluator-Model-
total 34760
drwxr-xr-x 4 root root     4096 Oct 26 13:09  .
drwxr-xr-x 1 root root     4096 Oct 26 13:09  ..
-rw-r--r-- 1 root root     7363 Oct 26 13:09  distilbert_embeddings.py
drwxr-xr-x 3 root root     4096 Oct 26 13:09  evaluator_ai
-rw-r--r-- 1 root root       22 Oct 26 13:09  File.zip
drwxr-xr-x 8 root root     4096 Oct 26 13:09  .git
-rw-r--r-- 1 root root     8257 Oct 26 13:09  nlp_feature_extraction.py
-rw-r--r-- 1 root root    12132 Oct 26 13:09  prepare_startup_dataset.py
-rw-r--r-- 1 root root       37 Oct 26 13:09  README.md
-rw-r--r-- 1 root root        0 Oct 26 13:09  semantic_similarity.py
-rw-r--r-- 1 root root   241067 Oct 26 13:09 'Shark Tank India.csv'
-rw-r--r-- 1 root root   145852 Oct 26 13:09  Sharktankpitchesdeals.csv
-rw-r--r-- 1 root root  2808998 Oct 26 13:09  startup_embedding_ids.csv
-rw-r--r-- 1 root root  6151062 Oct 26 13:09  startup_test.csv
-rw-r--r-- 1 root root  8270891 Oct 26 13:09  startup_tfidf_features.npz
-rw-r--r-- 1 root root  6160726 Oct 26 13:09  startup_validation.csv
-rw-r--r-- 1 root root 11674350 Oct 26 13:09  startup_valuation_dataset.csv
-rw-r--r-- 1 root root    66588 Oct 26 13:09  tfidf_vocabulary.csv

In [3]:
!find . -maxdepth 3 -type f

./prepare_startup_dataset.py
./startup_valuation_dataset.csv
./startup_tfidf_features.npz
./startup_embedding_ids.csv
./tfidf_vocabulary.csv
./.git/packed-refs
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/update.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-commit.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/sendemail-validate.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/commit-msg.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-rebase.sample
./.git/info/exclude
./.git/index
./.git/HEAD
./.git/logs/HEAD
./.git/description
./.git/config
./Sharktankpitchesdeals.csv
./evaluator_ai/Ai
./evaluator_ai/requirements.txt
./evaluator_ai/demo.py
./evaluator_ai/.gitignore
./evaluator_ai/File.zip
./evaluator_ai/train_pipeline.py
./evaluator_ai/pytest/CACHEDIR.TAG
./evaluator_ai/pytest/py
./evaluator_ai/pytest/.gitignore
./evaluator_ai/pytest/README.md
./evaluator_ai/pitch-evaluator-ai.zip
./nlp_feature_extraction.py
./startup_validation.csv
./semantic_similarity.py
./File.zip
./README.md
./distilbert_embeddings.py
./Shark Tank India.csv
./startup_test.csv

In [4]:
!pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [5]:
!pwd
!ls -la

/content/Entrepreneur-Pitch-Evaluator-Model-
total 34760
drwxr-xr-x 4 root root     4096 Oct 26 13:09  .
drwxr-xr-x 1 root root     4096 Oct 26 13:09  ..
-rw-r--r-- 1 root root     7363 Oct 26 13:09  distilbert_embeddings.py
drwxr-xr-x 3 root root     4096 Oct 26 13:09  evaluator_ai
-rw-r--r-- 1 root root       22 Oct 26 13:09  File.zip
drwxr-xr-x 8 root root     4096 Oct 26 13:09  .git
-rw-r--r-- 1 root root     8257 Oct 26 13:09  nlp_feature_extraction.py
-rw-r--r-- 1 root root    12132 Oct 26 13:09  prepare_startup_dataset.py
-rw-r--r-- 1 root root       37 Oct 26 13:09  README.md
-rw-r--r-- 1 root root        0 Oct 26 13:09  semantic_similarity.py
-rw-r--r-- 1 root root   241067 Oct 26 13:09 'Shark Tank India.csv'
-rw-r--r-- 1 root root   145852 Oct 26 13:09  Sharktankpitchesdeals.csv
-rw-r--r-- 1 root root  2808998 Oct 26 13:09  startup_embedding_ids.csv
-rw-r--r-- 1 root root  6151062 Oct 26 13:09  startup_test.csv
-rw-r--r-- 1 root root  8270891 Oct 26 13:09  startup_tfidf_features.npz
-rw-r--r-- 1 root root  6160726 Oct 26 13:09  startup_validation.csv
-rw-r--r-- 1 root root 11674350 Oct 26 13:09  startup_valuation_dataset.csv
-rw-r--r-- 1 root root    66588 Oct 26 13:09  tfidf_vocabulary.csv

In [6]:
!find /content -name "requirements.txt" -type f

/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt

In [7]:
!pip install -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt

Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (2.11.0+cpu)
Requirement already satisfied: transformers>=4.35.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (5.20.2)
Requirement already satisfied: sentence-transformers>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 3)) (5.7.0)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 4)) (1.6.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 5)) (2.2.3)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 6)) (2.1.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 7)) (1.16.3)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (3.10.0)
Requirement already satisfied: seaborn>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 9)) (0.13.2)
Requirement already satisfied: nltk>=3.8.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 10)) (3.9.1)
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 11)) (6.0.3)
Requirement already satisfied: pytest>=7.3.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 12)) (8.4.2)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 13)) (4.67.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 14)) (1.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (4.2.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (2025.12.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (1.33.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (26.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.23.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (2026.10.19)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.16.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.2.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 4)) (3.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 5)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 5)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 5)) (2026.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.7.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 8)) (3.3.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.13/dist-packages (from pytest>=7.3.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 12)) (2.3.1)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.13/dist-packages (from pytest>=7.3.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 12)) (1.7.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.13/dist-packages (from pytest>=7.3.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 12)) (2.21.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.3.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 14)) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 5)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.35.0->-r /content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt (line 2)) (0.1.2)

In [8]:
!find /content/Entrepreneur-Pitch-Evaluator-Model- -maxdepth 3 -type f | head -100

/content/Entrepreneur-Pitch-Evaluator-Model-/prepare_startup_dataset.py
/content/Entrepreneur-Pitch-Evaluator-Model-/startup_valuation_dataset.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/startup_tfidf_features.npz
/content/Entrepreneur-Pitch-Evaluator-Model-/startup_embedding_ids.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/tfidf_vocabulary.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/packed-refs
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/fsmonitor-watchman.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/update.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/post-update.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-commit.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/push-to-checkout.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/sendemail-validate.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-applypatch.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/commit-msg.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-push.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-merge-commit.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/prepare-commit-msg.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/applypatch-msg.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-receive.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/hooks/pre-rebase.sample
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/info/exclude
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/index
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/HEAD
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/logs/HEAD
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/description
/content/Entrepreneur-Pitch-Evaluator-Model-/.git/config
/content/Entrepreneur-Pitch-Evaluator-Model-/Sharktankpitchesdeals.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/Ai
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/requirements.txt
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/demo.py
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/.gitignore
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/File.zip
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/train_pipeline.py
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/pytest/CACHEDIR.TAG
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/pytest/py
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/pytest/.gitignore
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/pytest/README.md
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/pitch-evaluator-ai.zip
/content/Entrepreneur-Pitch-Evaluator-Model-/nlp_feature_extraction.py
/content/Entrepreneur-Pitch-Evaluator-Model-/startup_validation.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/semantic_similarity.py
/content/Entrepreneur-Pitch-Evaluator-Model-/File.zip
/content/Entrepreneur-Pitch-Evaluator-Model-/README.md
/content/Entrepreneur-Pitch-Evaluator-Model-/distilbert_embeddings.py
/content/Entrepreneur-Pitch-Evaluator-Model-/Shark Tank India.csv
/content/Entrepreneur-Pitch-Evaluator-Model-/startup_test.csv

In [9]:
%cd /content/Entrepreneur-Pitch-Evaluator-Model-

print("=== NLP FEATURE EXTRACTION ===")
!sed -n '1,220p' nlp_feature_extraction.py

print("\n=== DISTILBERT EMBEDDINGS ===")
!sed -n '1,220p' distilbert_embeddings.py

print("\n=== SEMANTIC SIMILARITY ===")
!sed -n '1,220p' semantic_similarity.py

print("\n=== TRAINING PIPELINE ===")
!sed -n '1,220p' evaluator_ai/train_pipeline.py

print("\n=== DEMO ===")
!sed -n '1,180p' evaluator_ai/demo.py

/content/Entrepreneur-Pitch-Evaluator-Model-
=== NLP FEATURE EXTRACTION ===
# ============================================================
# NLP FEATURE EXTRACTION FOR STARTUP DATA
# ============================================================
#
# This program:
# 1. Loads the cleaned startup dataset
# 2. Cleans startup text
# 3. Performs basic tokenization
# 4. Calculates basic NLP features
# 5. Extracts keywords using TF-IDF
# 6. Creates TF-IDF feature vectors
# 7. Saves the NLP-ready dataset
#
# ============================================================

import re
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import save_npz


# ============================================================
# 1. FILE NAMES
# ============================================================

INPUT_FILE = "startup_cleaned_dataset.csv"

OUTPUT_DATA_FILE = "startup_nlp_features.csv"
OUTPUT_TFIDF_FILE = "startup_tfidf_features.npz"
OUTPUT_VOCAB_FILE = "tfidf_vocabulary.csv"


# ============================================================
# 2. LOAD DATASET
# ============================================================

print("\nLoading cleaned dataset...")

df = pd.read_csv(INPUT_FILE)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)


# ============================================================
# 3. CHECK REQUIRED COLUMN
# ============================================================

if "startup_description" not in df.columns:

    raise ValueError(
        "startup_description column was not found."
    )


# ============================================================
# 4. NLP TEXT CLEANING
# ============================================================

def clean_text(text):

    # Convert everything to string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )

    # Remove extra spaces
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    # Remove leading/trailing spaces
    text = text.strip()

    return text


print("\nCleaning startup descriptions...")

df["nlp_text"] = df["startup_description"].apply(
    clean_text
)


# ============================================================
# 5. TOKENIZATION
# ============================================================
#
# Tokenization means splitting text into individual words.
#
# Example:
#
# "AI startup in healthcare"
#
# becomes:
#
# ["ai", "startup", "in", "healthcare"]
#
# ============================================================

print("\nPerforming tokenization...")

df["tokens"] = df["nlp_text"].apply(
    lambda text: text.split()
)


# ============================================================
# 6. BASIC NLP FEATURES
# ============================================================

print("\nCreating basic NLP features...")


# Number of words
df["word_count"] = df["nlp_text"].apply(
    lambda text: len(text.split())
)


# Number of characters
df["character_count"] = df["nlp_text"].apply(
    len
)


# Average word length
df["average_word_length"] = (
    df["character_count"] /
    df["word_count"].replace(0, np.nan)
)

df["average_word_length"] = (
    df["average_word_length"].fillna(0)
)


# ============================================================
# 7. TF-IDF
# ============================================================
#
# TF-IDF = Term Frequency - Inverse Document Frequency
#
# It identifies words that are important for distinguishing
# one startup description from another.
#
# Example:
#
# "startup" appears in almost every description
# -> lower importance
#
# "blockchain" may appear in fewer descriptions
# -> higher importance
#
# ============================================================

print("\nCreating TF-IDF features...")


tfidf = TfidfVectorizer(

    # Convert text to lowercase
    lowercase=True,

    # Remove common English words
    stop_words="english",

    # Use individual words + two-word phrases
    ngram_range=(1, 2),

    # Keep maximum 5000 features
    max_features=5000,

    # Ignore words appearing in fewer than 2 documents
    min_df=2,

    # Ignore words appearing in more than 95% documents
    max_df=0.95
)


# Create TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(
    df["nlp_text"]
)


print(
    "TF-IDF matrix shape:",
    tfidf_matrix.shape
)


# ============================================================
# 8. SAVE TF-IDF MATRIX
# ============================================================

save_npz(
    OUTPUT_TFIDF_FILE,
    tfidf_matrix
)

print(
    "TF-IDF matrix saved as:",
    OUTPUT_TFIDF_FILE
)



=== DISTILBERT EMBEDDINGS ===
import numpy as np
import pandas as pd
import torch

from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel


# ============================================================
# 1. SETTINGS
# ============================================================

INPUT_FILE = "startup_nlp_features.csv"

OUTPUT_EMBEDDINGS = "startup_distilbert_embeddings.npy"
OUTPUT_IDS = "startup_embedding_ids.csv"

MODEL_NAME = "distilbert-base-uncased"

# If your computer is slow / low on RAM, use 8 instead
BATCH_SIZE = 16

# Maximum number of words/tokens read from each startup text
MAX_LENGTH = 128


# ============================================================
# 2. SELECT CPU OR GPU
# ============================================================

if torch.cuda.is_available():

    device = torch.device("cuda")

    print("\nGPU detected!")
    print("Using GPU.")

else:

    device = torch.device("cpu")

    print("\nNo NVIDIA GPU detected.")
    print("Using CPU.")
    print("This is completely okay, but it may take longer.")


# ============================================================
# 3. LOAD DATASET
# ============================================================

print("\nLoading NLP dataset...")

df = pd.read_csv(INPUT_FILE)

print("Dataset loaded!")
print("Shape:", df.shape)


# ============================================================
# 4. CHECK TEXT COLUMN
# ============================================================

if "nlp_text" not in df.columns:

    raise ValueError(
        "nlp_text column not found. "
        "Run nlp_feature_extraction.py first."
    )


# Make sure there are no missing text values
df["nlp_text"] = (
    df["nlp_text"]
    .fillna("")
    .astype(str)
)


# ============================================================
# 5. LOAD DISTILBERT TOKENIZER
# ============================================================

print("\nLoading DistilBERT tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("Tokenizer loaded!")


# ============================================================
# 6. LOAD DISTILBERT MODEL
# ============================================================

print("\nLoading DistilBERT model...")

model = AutoModel.from_pretrained(
    MODEL_NAME
)

model.to(device)

# We are generating embeddings, not training yet
model.eval()

print("DistilBERT model loaded!")


# ============================================================
# 7. FUNCTION TO CREATE EMBEDDINGS
# ============================================================

def generate_embeddings(texts):

    all_embeddings = []

    for start in tqdm(
        range(
            0,
            len(texts),
            BATCH_SIZE
        ),
        desc="Generating embeddings"
    ):

        # Select one batch
        batch_texts = texts[
            start:start + BATCH_SIZE
        ]

        # ----------------------------------------------------
        # TOKENIZATION
        # ----------------------------------------------------

        encoded = tokenizer(
            batch_texts,
            padding=True,
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors="pt"
        )

        # Move tokens to CPU/GPU
        encoded = {
            key: value.to(device)
            for key, value in encoded.items()
        }

        # ----------------------------------------------------
        # DISTILBERT
        # ----------------------------------------------------

        # No gradients because we are not training yet
        with torch.no_grad():

            outputs = model(**encoded)

        # Shape:
        # batch size × tokens × 768

        last_hidden_state = (
            outputs.last_hidden_state
        )

        # ----------------------------------------------------
        # MEAN POOLING
        # ----------------------------------------------------
        #
        # DistilBERT gives one vector for every token.
        # We need one vector for the whole startup.
        #
        # Mean pooling combines the token vectors into
        # ONE 768-dimensional startup vector.
        # ----------------------------------------------------

        attention_mask = encoded[
            "attention_mask"
        ]

        mask = attention_mask.unsqueeze(
            -1
        ).expand(
            last_hidden_state.size()
        ).float()

        summed = torch.sum(
            last_hidden_state * mask,
            dim=1
        )

        counts = torch.clamp(
            mask.sum(dim=1),
            min=1e-9
        )

        embeddings = summed / counts

        # Move result back to CPU
        embeddings = (
            embeddings
            .cpu()
            .numpy()
        )

        all_embeddings.append(
            embeddings
        )

    return np.vstack(
        all_embeddings
    )


# ============================================================
# 8. GENERATE EMBEDDINGS
# ============================================================

print("\nStarting DistilBERT embedding generation...")


=== SEMANTIC SIMILARITY ===

=== TRAINING PIPELINE ===
r"""Master training and evaluation pipeline runner.

Executes the end-to-end workflow:
1. Loads raw datasets from D:/jiya/NLP&DL without modifying originals
2. Cleans datasets and extracts pre-decision features (preventing data leakage)
3. Generates canonical pitch dataset and formal data dictionary
4. Creates stratified train/validation/test splits (70/15/15, seed=42)
5. Fits Domain Classifier, Structured Model, Text Model, DistilBERT, and Fusion Model
6. Generates reference semantic embeddings with all-MiniLM-L6-v2
7. Evaluates all models, saves confusion matrices, ROC curves, error analysis, and comparison tables
8. Logs all experiment runs to experiments.json
"""

import os
import sys
import json
import time
from pathlib import Path
import numpy as np
import pandas as pd
import yaml

# Ensure src is in python path
CURRENT_DIR = Path(__file__).resolve().parent
if str(CURRENT_DIR) not in sys.path:
    sys.path.insert(0, str(CURRENT_DIR))

from src.data.loader import load_raw_datasets
from src.data.cleaner import clean_shark_tank_india, clean_shark_tank_us, clean_startup_valuation
from src.data.canonical import create_canonical_dataset, generate_data_dictionary
from src.data.splitter import create_train_val_test_splits
from src.nlp.embeddings import EmbeddingGenerator
from src.models.domain_classifier import DomainClassifier
from src.models.structured_model import StructuredDealClassifier
from src.models.text_model import TextDealClassifier
from src.models.distilbert_classifier import DistilBertDealClassifier
from src.models.fusion_classifier import MultimodalFusionClassifier
from src.evaluation.metrics import (
    compute_classification_metrics,
    plot_confusion_matrix,
    plot_roc_curve,
    plot_precision_recall_curve
)
from src.evaluation.comparison import ModelComparator
from src.evaluation.error_analysis import perform_error_analysis


def run_pipeline(config_path: str = "configs/config.yaml"):
    start_time = time.time()
    print("=" * 70)
    print("      STARTUP PITCH EVALUATOR - FULL TRAINING PIPELINE")
    print("=" * 70)

    # Load configuration
    cfg_file = Path(config_path)
    if not cfg_file.is_absolute():
        cfg_file = CURRENT_DIR / config_path
    with open(cfg_file, "r") as f:
        config = yaml.safe_load(f)

    raw_dir = Path(config["paths"]["raw_data_dir"])
    processed_dir = CURRENT_DIR / config["paths"]["processed_data_dir"]
    models_dir = CURRENT_DIR / config["paths"]["models_dir"]
    embeddings_dir = CURRENT_DIR / config["paths"]["embeddings_dir"]
    eval_dir = CURRENT_DIR / config["paths"]["evaluation_dir"]
    exp_dir = CURRENT_DIR / config["paths"]["experiments_dir"]

    for d in [processed_dir, models_dir, embeddings_dir, eval_dir, exp_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # ---------------------------------------------------------
    # 1. LOAD RAW DATASETS
    # ---------------------------------------------------------
    print("\n[Step 1/8] Loading raw datasets...")
    raw_data = load_raw_datasets(raw_dir)

    # ---------------------------------------------------------
    # 2. DATA CLEANING & LEAKAGE ISOLATION
    # ---------------------------------------------------------
    print("\n[Step 2/8] Cleaning datasets and isolating leakage...")
    sti_clean, sti_audit = clean_shark_tank_india(raw_data["shark_tank_india"])
    stp_clean, stp_audit = clean_shark_tank_us(raw_data["shark_tank_us"])
    # Sample 5000 rows from the 50k startup valuation dataset for fast, practical processing
    sv_sampled = raw_data["startup_valuation"].sample(n=min(5000, len(raw_data["startup_valuation"])), random_state=42)
    sv_clean, sv_audit = clean_startup_valuation(sv_sampled)

    # Save cleaned subsets
    sti_clean.to_csv(processed_dir / "shark_tank_india_clean.csv", index=False)
    stp_clean.to_csv(processed_dir / "shark_tank_us_clean.csv", index=False)
    sv_clean.to_csv(processed_dir / "startup_valuation_clean.csv", index=False)

    # ---------------------------------------------------------
    # 3. CREATE CANONICAL DATASET & DATA DICTIONARY
    # ---------------------------------------------------------
    print("\n[Step 3/8] Building canonical pitch dataset & data dictionary...")
    canonical_df = create_canonical_dataset(sti_clean, stp_clean, sv_clean)
    canonical_path = processed_dir / "canonical_pitches.csv"
    canonical_df.to_csv(canonical_path, index=False)
    print(f"  Canonical dataset saved: {canonical_df.shape[0]} rows to {canonical_path}")

    data_dict_df = generate_data_dictionary()
    dict_path = processed_dir / "data_dictionary.csv"
    data_dict_df.to_csv(dict_path, index=False)
    print(f"  Data dictionary saved: {len(data_dict_df)} features to {dict_path}")

    # ---------------------------------------------------------
    # 4. STRATIFIED SPLITTING (LEAKAGE PREVENTION)
    # ---------------------------------------------------------
    print("\n[Step 4/8] Creating stratified Train (70%), Val (15%), Test (15%) splits...")
    train_sti, val_sti, test_sti = create_train_val_test_splits(
        sti_clean,
        target_col="investment_decision",
        train_size=config["data"]["train_split"],
        val_size=config["data"]["val_split"],
        test_size=config["data"]["test_split"],
        random_state=config["project"]["random_seed"]
    )
    train_sti.to_csv(processed_dir / "train.csv", index=False)
    val_sti.to_csv(processed_dir / "val.csv", index=False)
    test_sti.to_csv(processed_dir / "test.csv", index=False)

    # Also split STUS for text models
    train_stp, val_stp, test_stp = create_train_val_test_splits(
        stp_clean,
        target_col="investment_decision",
        random_state=config["project"]["random_seed"]
    )

    # ---------------------------------------------------------
    # 5. GENERATE REFERENCE SEMANTIC EMBEDDINGS
    # ---------------------------------------------------------
    print("\n[Step 5/8] Generating sentence embeddings for reference startup search index...")
    embedder = EmbeddingGenerator(model_name=config["nlp"]["embedding_model"])
    ref_pitches = sti_clean["pitch_text"].tolist()
    ref_embeddings = embedder.generate_embeddings(ref_pitches, batch_size=32)
    embedder.save_embeddings(ref_embeddings, embeddings_dir / "startup_embeddings.npy")

    ref_metadata = sti_clean[["startup_name", "industry", "pitch_text", "investment_decision"]].copy()
    ref_metadata.to_csv(embeddings_dir / "startup_metadata.csv", index=False)

    # ---------------------------------------------------------
    # 6. MODEL TRAINING & FINE-TUNING
    # ---------------------------------------------------------
    print("\n[Step 6/8] Training Domain & Investment Classification Models...")
    comparator = ModelComparator()
    roc_dict = {}
    pr_dict = {}

    # --- 6A. Domain Classifier ---
    print("\n>>> Training Domain Classifier (TF-IDF + Logistic Regression)...")
    domain_clf = DomainClassifier(random_state=config["project"]["random_seed"])
    domain_clf.fit(train_sti["pitch_text"].tolist(), train_sti["industry"].tolist())
    domain_eval = domain_clf.evaluate(test_sti["pitch_text"].tolist(), test_sti["industry"].tolist())
    print(f"  Domain Classifier Test Accuracy: {domain_eval['accuracy']:.4f}, Macro F1: {domain_eval['macro_f1']:.4f}")
    domain_clf.save(models_dir / "domain_classifier.joblib")

    # --- 6B. Structured Financial Model ---
    print("\n>>> Training Structured Financial Baseline (Gradient Boosting)...")
    struct_clf = StructuredDealClassifier(model_type="gradient_boosting", random_state=config["project"]["random_seed"])
    struct_clf.fit(train_sti, target_col="investment_decision")
    struct_metrics = struct_clf.evaluate(test_sti, target_col="investment_decision")
    print(f"  Structured Model Test Metrics: {struct_metrics}")
    struct_clf.save(models_dir / "structured_model.joblib")
    comparator.add_model_result(
        "Structured Baseline (GBM)",
        "Pre-decision Financials (14 cols)",
        struct_metrics,
        "Pre-decision revenue, sales, margins, ask, equity, valuation"
    )
    y_test_sti = test_sti["investment_decision"].values
    probs_struct = struct_clf.predict_proba(test_sti)
    roc_dict["Structured Baseline"] = (y_test_sti, probs_struct)
    pr_dict["Structured Baseline"] = (y_test_sti, probs_struct)
    plot_confusion_matrix(
        y_test_sti,
        (probs_struct >= 0.5).astype(int),
        title="Structured Model Confusion Matrix",
        filepath=eval_dir / "confusion_matrix_structured.png"
    )

    # --- 6C. Text Deal Classifier (TF-IDF + Logistic Regression) ---
    print("\n>>> Training Text Deal Classifier (TF-IDF + Logistic Regression)...")
    text_clf = TextDealClassifier(
        min_df=config["nlp"]["min_df"],
        max_features=config["nlp"]["max_features"],
        random_state=config["project"]["random_seed"]
    )
    text_clf.fit(train_sti["pitch_text"].tolist(), train_sti["investment_decision"].tolist())
    text_metrics = text_clf.evaluate(test_sti["pitch_text"].tolist(), test_sti["investment_decision"].tolist())
    print(f"  Text Classifier Test Metrics: {text_metrics}")
    text_clf.save(models_dir / "text_model.joblib")
    comparator.add_model_result(
        "TF-IDF + Logistic Regression",
        "Pitch Text Unigrams + Bigrams",
        text_metrics,
        "Textual pitch unigrams & bigrams (1000 features)"
    )
    probs_text = text_clf.predict_proba(test_sti["pitch_text"].tolist())
    roc_dict["TF-IDF Text Model"] = (y_test_sti, probs_text)
    pr_dict["TF-IDF Text Model"] = (y_test_sti, probs_text)
    plot_confusion_matrix(
        y_test_sti,
        (probs_text >= 0.5).astype(int),
        title="TF-IDF Text Model Confusion Matrix",
        filepath=eval_dir / "confusion_matrix_text.png"
    )

    # --- 6D. Fine-tune DistilBERT ---
    print("\n>>> Fine-tuning DistilBERT on Pitch Text...")
    distilbert_clf = DistilBertDealClassifier(
        model_name=config["nlp"]["distilbert_model"],
        max_length=config["nlp"]["max_token_length"],

In [10]:
%cd /content/Entrepreneur-Pitch-Evaluator-Model-
!find evaluator_ai -type f \( \
  -name "*.joblib" -o \
  -name "*.pkl" -o \
  -name "*.npy" -o \
  -name "*.pt" -o \
  -name "*.pth" \
\)

/content/Entrepreneur-Pitch-Evaluator-Model-

In [11]:
!wc -l semantic_similarity.py
!cat semantic_similarity.py

0 semantic_similarity.py

In [12]:
!find evaluator_ai -maxdepth 4 -type f \
  ! -path "*/.git/*" \
  ! -path "*/pytest/*" | sort | head -200

evaluator_ai/Ai
evaluator_ai/demo.py
evaluator_ai/File.zip
evaluator_ai/.gitignore
evaluator_ai/pitch-evaluator-ai.zip
evaluator_ai/requirements.txt
evaluator_ai/train_pipeline.py

In [13]:
!ls -lh *.csv *.npz 2>/dev/null

-rw-r--r-- 1 root root 236K Oct 26 13:09 'Shark Tank India.csv'
-rw-r--r-- 1 root root 143K Oct 26 13:09  Sharktankpitchesdeals.csv
-rw-r--r-- 1 root root 2.7M Oct 26 13:09  startup_embedding_ids.csv
-rw-r--r-- 1 root root 5.9M Oct 26 13:09  startup_test.csv
-rw-r--r-- 1 root root 7.9M Oct 26 13:09  startup_tfidf_features.npz
-rw-r--r-- 1 root root 5.9M Oct 26 13:09  startup_validation.csv
-rw-r--r-- 1 root root  12M Oct 26 13:09  startup_valuation_dataset.csv
-rw-r--r-- 1 root root  66K Oct 26 13:09  tfidf_vocabulary.csv

In [14]:
!pip -q install sentence-transformers gradio feedparser duckduckgo-search

In [15]:

from google.colab import drive
import os

REPO = "/content/Entrepreneur-Pitch-Evaluator-Model-"

if os.path.isdir(REPO) and os.path.isdir(os.path.join(REPO, ".git")):
    print("Repository already available:", REPO)
else:
    from google.colab import userdata
    import subprocess

    REPO_URL = input(
        "Paste your GitHub repository URL: "
    ).strip()

    result = subprocess.run(
        ["git", "clone", REPO_URL, REPO],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(
            "Repository cloning failed. Check the URL and repository access."
        )

print("\nProject files:")
for root, dirs, files in os.walk(REPO):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]
    level = root.replace(REPO, "").count(os.sep)
    if level > 2:
        dirs[:] = []
        continue
    print("  " * level + os.path.basename(root) + "/")
    for file in files[:20]:
        print("  " * (level + 1) + file)

Repository already available: /content/Entrepreneur-Pitch-Evaluator-Model-

Project files:
Entrepreneur-Pitch-Evaluator-Model-/
  prepare_startup_dataset.py
  startup_valuation_dataset.csv
  startup_tfidf_features.npz
  startup_embedding_ids.csv
  tfidf_vocabulary.csv
  Sharktankpitchesdeals.csv
  nlp_feature_extraction.py
  startup_validation.csv
  semantic_similarity.py
  File.zip
  README.md
  distilbert_embeddings.py
  Shark Tank India.csv
  startup_test.csv
  evaluator_ai/
    Ai
    requirements.txt
    demo.py
    .gitignore
    File.zip
    train_pipeline.py
    pitch-evaluator-ai.zip
    pytest/
      CACHEDIR.TAG
      py
      .gitignore
      README.md

In [16]:
%pip -q install -U sentence-transformers transformers torch gradio pandas numpy feedparser scikit-learn

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.1.0 which is incompatible.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.14.1 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.4 which is incompatible.

In [17]:
import os
import pandas as pd
BASE = REPO
print("Repository exists:", os.path.isdir(BASE))

for root, dirs, files in os.walk(BASE):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]
    for file in files:
        if file.lower().endswith((".csv", ".parquet")):
            path = os.path.join(root, file)
            print(f"{file} | {os.path.getsize(path) / (1024**2):.2f} MB | {path}")

/usr/local/lib/python3.13/dist-packages/pandas/core/arrays/masked.py:63: UserWarning: Pandas requires version '1.5.0' or newer of 'bottleneck' (version '1.4.2' currently installed).
  from pandas.core import (

Repository exists: True
startup_valuation_dataset.csv | 11.13 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/startup_valuation_dataset.csv
startup_embedding_ids.csv | 2.68 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/startup_embedding_ids.csv
tfidf_vocabulary.csv | 0.06 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/tfidf_vocabulary.csv
Sharktankpitchesdeals.csv | 0.14 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/Sharktankpitchesdeals.csv
startup_validation.csv | 5.88 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/startup_validation.csv
Shark Tank India.csv | 0.23 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/Shark Tank India.csv
startup_test.csv | 5.87 MB | /content/Entrepreneur-Pitch-Evaluator-Model-/startup_test.csv

In [18]:

import glob
import os
import pandas as pd

csv_files = glob.glob(os.path.join(BASE, "**", "*.csv"), recursive=True)

datasets = {}

for path in csv_files:
    try:
        df = pd.read_csv(path, nrows=5, low_memory=False)
        datasets[os.path.relpath(path, BASE)] = df
        print(f"\nFILE: {os.path.relpath(path, BASE)}")
        print("Columns:", df.columns.tolist())
        print(df.head(2).to_string(index=False)[:1200])
    except Exception as e:
        print(f"Could not inspect {path}: {e}")

FILE: startup_valuation_dataset.csv
Columns: ['startup_id', 'startup_name', 'founded_year', 'country', 'region', 'industry', 'funding_round', 'funding_amount_usd', 'funding_date', 'lead_investor', 'co_investors', 'employee_count', 'estimated_revenue_usd', 'estimated_valuation_usd', 'exited', 'exit_type', 'tags']
                          startup_id  startup_name  founded_year country        region   industry funding_round  funding_amount_usd funding_date lead_investor                 co_investors  employee_count  estimated_revenue_usd  estimated_valuation_usd  exited exit_type                         tags
456bf4d2-b982-41e7-83fe-04bac2053405 Rice-Martinez          2008  Latvia North America Blockchain      Series A           764048000   2020-03-15       Sequoia                 Y Combinator             106           2.898777e+08             5.187327e+09   False       NaN               EdTech, Mobile
ed442136-e5ec-43c5-afdf-a2dc08c5d4a2  Edwards-Page          2006  Guyana North America    Fintech      Series A           379993000   2017-04-09  Tiger Global Accel, Tiger Global, Sequoia             735           4.567835e+07             1.234201e+09   False       NaN Cloud, IoT, SaaS, AI, Mobile

FILE: startup_embedding_ids.csv
Columns: ['startup_id', 'startup_name']
                          startup_id  startup_name
456bf4d2-b982-41e7-83fe-04bac2053405 Rice-Martinez
ed442136-e5ec-43c5-afdf-a2dc08c5d4a2  Edwards-Page

FILE: tfidf_vocabulary.csv
Columns: ['feature']
feature
     60
 60 deg

FILE: Sharktankpitchesdeals.csv
Columns: ['Season_Epi_code', 'Pitched_Business_Identifier', 'Pitched_Business_Desc', 'Deal_Status', 'Deal_Shark']
 Season_Epi_code Pitched_Business_Identifier                                                                                                                                                                                                                                                                                                  Pitched_Business_Desc  Deal_Status Deal_Shark
             826                Bridal Buddy a functional slip worn under a wedding gown that allows the wearer to use the restroom on their own . Bridal Buddy is a lightweight slip worn under the gown that lets brides go to the bathroom while wearing it. When nature calls, the bride can bag up her bustle to safely relieve herself without making a mess.            1     KOL+LG
             826                  Laid Brand                                                                              hair-care products made with pheromones . Laid brand is a Â pheromone-enriched hair care product thatÂ enhances color, in addition to protecting and hydrating hair.Â The pheromones help girls â€œexude confidenceâ€ wherever she goes.            0        NaN

FILE: startup_validation.csv
Columns: ['startup_id', 'startup_name', 'founded_year', 'country', 'region', 'industry', 'funding_round', 'funding_amount_usd', 'funding_date', 'lead_investor', 'co_investors', 'employee_count', 'estimated_revenue_usd', 'estimated_valuation_usd', 'exited', 'exit_type', 'tags', 'investment_worthy', 'startup_description', 'clean_description', 'business_category', 'startup_age', 'revenue_to_funding_ratio', 'valuation_to_funding_ratio', 'valuation_to_revenue_ratio', 'log_funding_amount_usd', 'log_estimated_revenue_usd', 'log_estimated_valuation_usd']
                          startup_id    startup_name  founded_year                  country        region industry funding_round  funding_amount_usd funding_date  lead_investor                      co_investors  employee_count  estimated_revenue_usd  estimated_valuation_usd  exited exit_type                                  tags  investment_worthy                                                                                                                                                                                                                     startup_description                                                                                                                                                                                                             clean_description     business_category  startup_age  revenue_to_funding_ratio  valuation_to_funding_ratio  valuation_to_revenue_ratio  log_funding_amount_usd  log_estimated_revenue_usd  log_estimated_valuation_usd
f616626f-e4e5-41f8-b137-ab545f964f5c     Jackson Ltd          2010                    Benin North America    AI/ML      Series D           497531000   2016-02-01        Sequoia               Andreess

FILE: Shark Tank India.csv
Columns: ['Season Number', 'Startup Name', 'Episode Number', 'Pitch Number', 'Season Start', 'Season End', 'Original Air Date', 'Episode Title', 'Anchor', 'Industry', 'Business Description', 'Company Website', 'Started in', 'Number of Presenters', 'Male Presenters', 'Female Presenters', 'Transgender Presenters', 'Couple Presenters', 'Pitchers Average Age', 'Pitchers City', 'Pitchers State', 'Yearly Revenue', 'Monthly Sales', 'Gross Margin', 'Net Margin', 'EBITDA', 'Cash Burn', 'SKUs', 'Has Patents', 'Bootstrapped', 'Part of Match off', 'Original Ask Amount', 'Original Offered Equity', 'Valuation Requested', 'Received Offer', 'Accepted Offer', 'Total Deal Amount', 'Total Deal Equity', 'Total Deal Debt', 'Debt Interest', 'Deal Valuation', 'Number of Sharks in Deal', 'Deal Has Conditions', 'Royalty Percentage', 'Royalty Recouped Amount', 'Advisory Shares Equity', 'Namita Investment Amount', 'Namita Investment Equity', 'Namita Debt Amount', 'Vineeta Investment Amount', 'Vineeta Investment Equity', 'Vineeta Debt Amount', 'Anupam Investment Amount', 'Anupam Investment Equity', 'Anupam Debt Amount', 'Aman Investment Amount', 'Aman Investment Equity', 'Aman Debt Amount', 'Peyush Investment Amount', 'Peyush Investment Equity', 'Peyush Debt Amount', 'Ritesh Investment Amount', 'Ritesh Investment Equity', 'Ritesh Debt Amount', 'Amit Investment Amount', 'Amit Investment Equity', 'Amit Debt Amount', 'Guest Investment Amount', 'Guest Investment Equity', 'Guest Debt Amount', 'Invested Guest Name', 'All Guest Names', 'Namita Present', 'Vineeta Present', 'Anupam Present', 'Aman Present', 'Peyush Present', 'Ritesh Present', 'Amit Present', 'Guest Present']
 Season Number  Startup Name  Episode Number  Pitch Number Season Start Season End Original Air Date               Episode Title          Anchor                     Industry                          Business Description            Company Website  Started in  Number of Presenters  Male Presenters  Female Presenters  Transgender Presenters  Couple Presenters Pitchers Average Age Pitchers City Pitchers State  Yearly Revenue  Monthly Sales  Gross Margin  Net Margin  EBITDA  Cash Burn  SKUs  Has Patents  Bootstrapped  Part of Match off  Original Ask Amount  Original Offered Equity  Valuation Requested  Received Offer  Accepted Offer  Total Deal Amount  Total Deal Equity  Total Deal Debt  Debt Interest  Deal Valuation  Number of Sharks in Deal  Deal Has Conditions  Royalty Percentage  Royalty Recouped Amount  Advisory Shares Equity  Namita Investment Amount  Namita Investment Equity  Namita Debt Amount  Vineeta Investment Amount  Vineeta Investment Equity  Vineeta Debt Amount  Anupam Investment Amount  Anupam Investment Equity  Anupam Debt Amount  Aman Investment Amount  Aman Investment Equity  Aman Debt Amount  Peyush Investment Amount  Peyush Investment Equity  Peyush Debt Amount  Rit

FILE: startup_test.csv
Columns: ['startup_id', 'startup_name', 'founded_year', 'country', 'region', 'industry', 'funding_round', 'funding_amount_usd', 'funding_date', 'lead_investor', 'co_investors', 'employee_count', 'estimated_revenue_usd', 'estimated_valuation_usd', 'exited', 'exit_type', 'tags', 'investment_worthy', 'startup_description', 'clean_description', 'business_category', 'startup_age', 'revenue_to_funding_ratio', 'valuation_to_funding_ratio', 'valuation_to_revenue_ratio', 'log_funding_amount_usd', 'log_estimated_revenue_usd', 'log_estimated_valuation_usd']
                          startup_id  startup_name  founded_year country        region   industry funding_round  funding_amount_usd funding_date lead_investor             co_investors  employee_count  estimated_revenue_usd  estimated_valuation_usd  exited exit_type               tags  investment_worthy                                                                                                                                                                                                      startup_description                                                                                                                                                                                                 clean_description     business_category  startup_age  revenue_to_funding_ratio  valuation_to_funding_ratio  valuation_to_revenue_ratio  log_funding_amount_usd  log_estimated_revenue_usd  log_estimated_valuation_usd
9a2d189a-cb0f-4b8c-a90f-d04b109dab82     Chase Ltd          2016  Mexico          MENA E-commerce      Series B            48085000   2023-03-03         Accel      Andreessen Horowitz             513           7.267198e+06             4.471235e+08       0   Unknown Mobile

In [19]:

import os
import pandas as pd
import numpy as np

BASE = "/content/Entrepreneur-Pitch-Evaluator-Model-"

startup_df = pd.read_csv(
    os.path.join(BASE, "startup_test.csv"),
    low_memory=False
)

sharktank_df = pd.read_csv(
    os.path.join(BASE, "Shark Tank India.csv"),
    low_memory=False
)

# Prepare startup descriptions
startup_df["startup_description"] = (
    startup_df["startup_description"]
    .fillna("")
    .astype(str)
)

startup_df["clean_description"] = (
    startup_df["clean_description"]
    .fillna("")
    .astype(str)
)

startup_df["pitch_text"] = startup_df["clean_description"].where(
    startup_df["clean_description"].str.strip().ne(""),
    startup_df["startup_description"]
)

startup_df = startup_df[
    startup_df["pitch_text"].str.strip().ne("")
].reset_index(drop=True)

# Prepare Shark Tank India descriptions
sharktank_df["Business Description"] = (
    sharktank_df["Business Description"]
    .fillna("")
    .astype(str)
)

sharktank_df = sharktank_df[
    sharktank_df["Business Description"].str.strip().ne("")
].reset_index(drop=True)

print("Startup records:", len(startup_df))
print("Shark Tank India records:", len(sharktank_df))

print("\nExample startup:")
print(startup_df.loc[0, "startup_name"])
print(startup_df.loc[0, "pitch_text"][:500])

print("\nExample Shark Tank India pitch:")
print(sharktank_df.loc[0, "Startup Name"])
print(sharktank_df.loc[0, "Business Description"][:500])

Startup records: 7500
Shark Tank India records: 789

Example startup:
Chase Ltd
chase ltd is a startup operating in the e commerce industry it is based in mena mexico the startup is associated with the following focus areas mobile healthtech its recorded funding stage is series b

Example Shark Tank India pitch:
BluePineFoods
Frozen Momos

In [20]:
%pip install -q --force-reinstall numpy==2.2.6 pandas==2.2.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-bigquery 3.46.2 requires python-dateutil<3.0.0,>=2.8.2, but you have python-dateutil 3.0.0 which is incompatible.
holidays 0.107 requires python-dateutil<3,>=2.9.0.post0, but you have python-dateutil 3.0.0 which is incompatible.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.14.1 which is incompatible.
betterproto 2.0.0b7 requires python-dateutil<3.0,>=2.8, but you have python-dateutil 3.0.0 which is incompatible.
bigframes 2.51.0 requires python-dateutil<3,>=2.8.2, but you have python-dateutil 3.0.0 which is incompatible.
ibis-framework 9.5.0 requires python-dateutil<3,>=2.8.2, but you have python-dateutil 3.0.0 which is incompatible.

In [21]:

%pip install -q --force-reinstall python-dateutil==2.9.0.post0

In [24]:

%pip install --upgrade --no-cache-dir numpy sentence-transformers transformers

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.2.6)
Collecting numpy
  Downloading numpy-2.5.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (6.2.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.20.2)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.23.3)
Requirement already satisfied: huggingface-hub<3.0.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.33.0)
Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.14.1)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (4.2.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (2026.10.19)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: setuptools>=77.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (13.4.4)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->sentence-transformers) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.4.92)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.2->sentence-transformers) (1.8.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading numpy-2.5.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 33.9 MB/s  0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.14.1 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.4 which is incompatible.
Successfully installed numpy-2.5.4

In [2]:

%pip install --force-reinstall --no-cache-dir "numpy<2" sentence-transformers

Collecting numpy<2
  Downloading numpy-1.26.4.tar.gz (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 31.0 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sentence-transformers
  Downloading sentence_transformers-6.2.0-py3-none-any.whl.metadata (20 kB)
Collecting transformers<6.0.0,>=5.0.0 (from sentence-transformers)
  Downloading transformers-5.20.2-py3-none-any.whl.metadata (31 kB)
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.23.3-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Collecting huggingface-hub<3.0.0,>=1.3.0 (from sentence-transformers)
  Downloading huggingface_hub-2.3.0-py3-none-any.whl.metadata (16 kB)
Collecting torch>=2.2 (from sentence-transformers)
  Downloading torch-2.14.1-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (37 kB)
Collecting scikit-learn>=1.1.0 (from sentence-transformers)
  Downloading scikit_learn-1.9.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.3 kB)
Collecting scipy>=1.0.0 (from sentence-transformers)
  Downloading scipy-1.18.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting typing_extensions>=4.10.0 (from sentence-transformers)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting tqdm>=4.0.0 (from sentence-transformers)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading filelock-4.2.4-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading hf_xet-1.7.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading httpx2-2.16.0-py3-none-any.whl.metadata (10 kB)
Collecting packaging>=20.9 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting anyio>=4.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting httpcore2==2.16.0 (from httpx2<3,>=2.0.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading httpcore2-2.16.0-py3-none-any.whl.metadata (27 kB)
Collecting idna>=3.18 (from httpx2<3,>=2.0.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading truststore-0.10.5-py3-none-any.whl.metadata (4.5 kB)
Collecting h11>=0.16 (from httpcore2==2.16.0->httpx2<3,>=2.0.0->huggingface-hub<3.0.0,>=1.3.0->sentence-transformers)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading regex-2026.9.29-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting typer (from transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading typer-0.27.3-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting joblib>=1.4.0 (from scikit-learn>=1.1.0->sentence-transformers)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn>=1.1.0->sentence-transformers)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=1.1.0->sentence-transformers)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
Collecting scipy>=1.0.0 (from sentence-transformers)
  Downloading scipy-1.18.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting setuptools>=77.0.3 (from torch>=2.2->sentence-transformers)
  Downloading setuptools-84.2.1-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=2.2->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=2.2->sentence-transformers)
  Downloading networkx-3.7-py3-none-any.whl.metadata (6.7 kB)
Collecting jinja2 (from torch>=2.2->sentence-transformers)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting cuda-toolkit==13.0.3 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl.metadata (17 kB)
Collecting cuda-bindings<14,>=13.0.3 (from torch>=2.2->sentence-transformers)
  Downloading cuda_bindings-13.4.4-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting nvidia-cudnn-cu13==9.24.0.43 (from torch>=2.2->sentence-transformers)
  Downloading nvidia_cudnn_cu13-9.24.0.43-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from torch>=2.2->sentence-transformers)
  Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu13==2.30.7 (from torch>=2.2->sentence-transformers)
  Downloading nvidia_nccl_cu13-2.30.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from torch>=2.2->sentence-transformers)
  Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting triton~=3.8.0 (from torch>=2.2->sentence-transformers)
  Downloading triton-3.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (978 bytes)
Collecting nvidia-cublas==13.1.1.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvrtc==13.0.88.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft==12.0.0.61.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink<14,>=13.0.88 (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_nvjitlink-13.4.92-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx==13.0.85.* (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch>=2.2->sentence-transformers)
  Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Collecting cuda-pathfinder>=1.4.2 (from cuda-bindings<14,>=13.0.3->torch>=2.2->sentence-transformers)
  Downloading cuda_pathfinder-1.8.4-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.2->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=2.2->sentence-transformers)
  Downloading markupsafe-3.0.4-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Collecting shellingham>=1.3.0 (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading sentence_transformers-6.2.0-py3-none-any.whl (760 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 760.7/760.7 kB 169.0 MB/s  0:00:00
Downloading huggingface_hub-2.3.0-py3-none-any.whl (855 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 855.2/855.2 kB 125.8 MB/s  0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.7.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 77.3 MB/s  0:00:00
Downloading httpx2-2.16.0-py3-none-any.whl (97 kB)
Downloading httpcore2-2.16.0-py3-none-any.whl (85 kB)
Downloading transformers-5.20.2-py3-none-any.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 106.6 MB/s  0:00:00
Downloading tokenizers-0.23.3-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 153.0 MB/s  0:00:00
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading filelock-4.2.4-py3-none-any.whl (162 kB)
Downloading fsspec-2026.9.0-py3-none-any.whl (221 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 490.9 MB/s  0:00:00
Downloading regex-2026.9.29-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 166.6 MB/s  0:00:00
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Downloading scikit_learn-1.9.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 145.1 MB/s  0:00:00
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Downloading scipy-1.17.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 159.6 MB/s  0:00:00
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Downloading torch-2.14.1-cp313-cp313-manylinux_2_28_x86_64.whl (554.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 554.6/554.6 MB 138.6 MB/s  0:00:07
Downloading cuda_toolkit-13.0.3.0-py2.py3-none-any.whl (2.5 kB)
Downloading nvidia_cudnn_cu13-9.24.0.43-py3-none-manylinux_2_27_x86_64.whl (553.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.1/553.1 MB 134.4 MB/s  0:00:05
Downloading nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl (170.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 45.4 MB/s  0:00:03
Downloading nvidia_nccl_cu13-2.30.7-py3-none-manylinux_2_18_x86_64.whl (216.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 MB 137.7 MB/s  0:00:01
Downloading nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 23.1 MB/s  0:00:02
Downloading cuda_bindings-13.4.4-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 22.3 MB/s  0:00:00
Downloading nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl (423.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 62.9 MB/s  0:00:05
Downloading nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 130.6 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (90.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 58.6 MB/s  0:00:01
Downloading nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 339.9 MB/s  0:00:00
Downloading nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (214.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 131.3 MB/s  0:00:01
Downloading nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 287.7 MB/s  0:00:00
Downloading nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl (59.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 231.8 MB/s  0:00:00
Downloading nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl (200.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 157.1 MB/s  0:00:01
Downloading nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (145.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 25.7 MB/s  0:00:05
Downloading nvidia_nvjitlink-13.4.92-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (42.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 MB 181.1 MB/s  0:00:00
Downloading nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (148 kB)
Downloading triton-3.8.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (248.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.0/248.0 MB 187.2 MB/s  0:00:01
Downloading cuda_pathfinder-1.8.4-py3-none-any.whl (62 kB)
Downloading networkx-3.7-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 186.6 MB/s  0:00:00
Downloading setuptools-84.2.1-py3-none-any.whl (876 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 876.3/876.3 kB 199.1 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 223.0 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 164.4 MB/s  0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Downloading truststore-0.10.5-py3-none-any.whl (19 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.4-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (23 kB)
Downloading typer-0.27.3-py3-none-any.whl (123 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 220.2 MB/s  0:00:00
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml) ... done
  Created wheel for numpy: filename=numpy-1.26.4-cp313-cp313-linux_x86_64.whl size=7039808 sha256=9bb94d8a8aafb2b5435025405f6ff77b56a6d61fc02a1f9d10d7ef10281c70ed
  Stored in directory: /tmp/pip-ephem-wheel-cache-bi0fba_w/wheels/8b/2d/9f/b6b46373f328e2ef50388915d351ccacbedac929459b5459bf
Successfully built numpy
Installing collected packages: nvidia-cusparselt-cu13, mpmath, cuda-toolkit, typing_extensions, truststore, triton, tqdm, threadpoolctl, sympy, shellingham, setuptools, safetensors, regex, pyyaml, pygments, packaging, nvidia-nvtx, nvidia-nvshmem-cu13, nvidia-nvjitlink, nvidia-nccl-cu13, nvidia-curand, nvidia-cufile, nvidia-cuda-runtime, nvidia-cuda-nvrtc, nvidia-cuda-cupti, numpy, networkx, narwhals, mdurl, MarkupSafe, idna, hf-xet, h11, fsspec, filelock, cuda-pathfinder, cloudpickle, click, annotated-doc, scipy, nvidia-cusparse, nvidia-cufft, nvidia-cublas, markdown-it-py, joblib, jinja2, httpcore2, cuda-bindings, anyio, scikit-learn, rich, nvidia-cusolver, nvidia-cudnn-cu13, httpx2, typer, huggingface-hub, torch, tokenizers, transformers, sentence-transformers
  Attempting uninstall: nvidia-cusparselt-cu13
    Found existing installation: nvidia-cusparselt-cu13 0.8.1

In [4]:

import torch
import importlib.metadata as md

print("Python:", __import__("sys").version)
print("PyTorch:", torch.__version__)

for package in ["torchvision", "transformers", "sentence-transformers", "numpy"]:
    try:
        print(package, md.version(package))
    except md.PackageNotFoundError:
        print(package, "not installed")

Python: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
PyTorch: 2.14.1+cu130
torchvision not installed
transformers 5.20.2
sentence-transformers 6.2.0
numpy 1.26.4

In [5]:

%pip uninstall -y torchvision

WARNING: Skipping torchvision as it is not installed.

In [1]:

import numpy as np
import torch

print("NumPy:", np.__version__)
print("PyTorch:", torch.__version__)

from sentence_transformers import SentenceTransformer

print("SUCCESS: SentenceTransformer imported!")

NumPy: 1.26.4
PyTorch: 2.14.1+cu130
SUCCESS: SentenceTransformer imported!

In [2]:
%pip uninstall -y torchvision

Found existing installation: torchvision 0.26.0+cpu
Uninstalling torchvision-0.26.0+cpu:
  Successfully uninstalled torchvision-0.26.0+cpu

In [2]:

import numpy as np
import pandas as pd
import torch

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("PyTorch:", torch.__version__)

from sentence_transformers import SentenceTransformer
from transformers import pipeline

print("SUCCESS: Deep learning imports are working!")
print("GPU available:", torch.cuda.is_available())

NumPy: 1.26.4
Pandas: 2.2.3
PyTorch: 2.14.1+cu130
SUCCESS: Deep learning imports are working!
GPU available: False

In [3]:

import os
import pandas as pd
import numpy as np
import torch

BASE = "/content/Entrepreneur-Pitch-Evaluator-Model-"

startup_df = pd.read_csv(
    os.path.join(BASE, "startup_test.csv"),
    low_memory=False
)

sharktank_df = pd.read_csv(
    os.path.join(BASE, "Shark Tank India.csv"),
    low_memory=False
)

# Prepare startup pitch text
startup_df["startup_description"] = (
    startup_df["startup_description"].fillna("").astype(str)
)
startup_df["clean_description"] = (
    startup_df["clean_description"].fillna("").astype(str)
)

startup_df["pitch_text"] = startup_df["clean_description"].where(
    startup_df["clean_description"].str.strip().ne(""),
    startup_df["startup_description"]
)

startup_df = startup_df[
    startup_df["pitch_text"].str.strip().ne("")
].reset_index(drop=True)

# Prepare Shark Tank India text
sharktank_df["Business Description"] = (
    sharktank_df["Business Description"].fillna("").astype(str)
)

sharktank_df = sharktank_df[
    sharktank_df["Business Description"].str.strip().ne("")
].reset_index(drop=True)

print("Startup dataset loaded:", len(startup_df), "rows")
print("Shark Tank India loaded:", len(sharktank_df), "rows")
print("Ready to build semantic retrieval!")

Startup dataset loaded: 7500 rows
Shark Tank India loaded: 789 rows
Ready to build semantic retrieval!

In [4]:

import os
import pandas as pd
import numpy as np

BASE = "/content/Entrepreneur-Pitch-Evaluator-Model-"

startup_df = pd.read_csv(
    os.path.join(BASE, "startup_test.csv"),
    low_memory=False
)

sharktank_df = pd.read_csv(
    os.path.join(BASE, "Shark Tank India.csv"),
    low_memory=False
)

# Prepare startup descriptions
startup_df["startup_description"] = (
    startup_df["startup_description"]
    .fillna("")
    .astype(str)
)

startup_df["clean_description"] = (
    startup_df["clean_description"]
    .fillna("")
    .astype(str)
)

startup_df["pitch_text"] = startup_df["clean_description"].where(
    startup_df["clean_description"].str.strip().ne(""),
    startup_df["startup_description"]
)

startup_df = startup_df[
    startup_df["pitch_text"].str.strip().ne("")
].reset_index(drop=True)

# Prepare Shark Tank India descriptions
sharktank_df["Business Description"] = (
    sharktank_df["Business Description"]
    .fillna("")
    .astype(str)
)

sharktank_df = sharktank_df[
    sharktank_df["Business Description"].str.strip().ne("")
].reset_index(drop=True)

print("Startup records:", len(startup_df))
print("Shark Tank India records:", len(sharktank_df))

print("\nExample startup:")
print(startup_df.loc[0, "startup_name"])
print(startup_df.loc[0, "pitch_text"][:500])

print("\nExample Shark Tank India pitch:")
print(sharktank_df.loc[0, "Startup Name"])
print(sharktank_df.loc[0, "Business Description"][:500])

Startup records: 7500
Shark Tank India records: 789

Example startup:
Chase Ltd
chase ltd is a startup operating in the e commerce industry it is based in mena mexico the startup is associated with the following focus areas mobile healthtech its recorded funding stage is series b

Example Shark Tank India pitch:
BluePineFoods
Frozen Momos

In [5]:

import torch
from sentence_transformers import SentenceTransformer

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

retrieval_df = pd.concat(
    [
        pd.DataFrame({
            "startup_name": startup_df["startup_name"].astype(str),
            "industry": startup_df["industry"].fillna("Unknown").astype(str),
            "pitch_text": startup_df["pitch_text"],
            "source": "Startup Dataset"
        }),
        pd.DataFrame({
            "startup_name": sharktank_df["Startup Name"].astype(str),
            "industry": sharktank_df["Industry"].fillna("Unknown").astype(str),
            "pitch_text": sharktank_df["Business Description"],
            "source": "Shark Tank India"
        })
    ],
    ignore_index=True
)

retrieval_df = retrieval_df[
    retrieval_df["pitch_text"].str.strip().ne("")
].drop_duplicates(
    subset=["startup_name", "pitch_text"]
).reset_index(drop=True)

retrieval_model = SentenceTransformer(
    "all-MiniLM-L6-v2",
    device=device
)

pitch_embeddings = retrieval_model.encode(
    retrieval_df["pitch_text"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Records indexed:", len(retrieval_df))
print("Embedding matrix shape:", pitch_embeddings.shape)

Device: cpu

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/130 [00:00<?, ?it/s]

Records indexed: 8289
Embedding matrix shape: (8289, 384)

In [6]:

from sentence_transformers import util

def retrieve_similar_pitches(pitch, top_k=10):
    query_embedding = retrieval_model.encode(
        pitch,
        convert_to_tensor=True,
        normalize_embeddings=True
    )

    scores = util.cos_sim(
        query_embedding,
        torch.tensor(pitch_embeddings, device=query_embedding.device)
    )[0]

    k = min(top_k, len(retrieval_df))
    values, indices = torch.topk(scores, k=k)

    results = retrieval_df.iloc[
        indices.cpu().numpy()
    ].copy()

    results["similarity"] = values.cpu().numpy().round(4)

    return results[
        ["startup_name", "industry", "source", "similarity", "pitch_text"]
    ]

test_pitch = """
We sell healthy ready-to-eat Indian snacks made from millets.
Our company targets urban consumers looking for convenient,
nutritious food products through online sales and retail stores.
"""

retrieve_similar_pitches(test_pitch, top_k=5)

,startup_name,industry,source,similarity,pitch_text
7883,MilletAmma,Food and Beverage,Shark Tank India,0.6050,Millet based Products
7732,TheGreenSnack,Food and Beverage,Shark Tank India,0.6045,Healthy Snacks Online
8089,EatBetterCo,Food and Beverage,Shark Tank India,0.5934,Healthy delicious snacks
7535,SweeDesi,Food and Beverage,Shark Tank India,0.5659,Indian Sweets Online
7809,LilGoodness,Food and Beverage,Shark Tank India,0.5652,Healthy Snacks

In [7]:

ARTIFACT_DIR = os.path.join(BASE, "evaluator_ai", "artifacts", "my_components")
os.makedirs(ARTIFACT_DIR, exist_ok=True)

retrieval_df.to_csv(
    os.path.join(ARTIFACT_DIR, "retrieval_dataset.csv"),
    index=False
)

np.save(
    os.path.join(ARTIFACT_DIR, "pitch_embeddings.npy"),
    pitch_embeddings
)

print("Saved retrieval dataset and embeddings to:")
print(ARTIFACT_DIR)

Saved retrieval dataset and embeddings to:
/content/Entrepreneur-Pitch-Evaluator-Model-/evaluator_ai/artifacts/my_components

In [8]:

from sentence_transformers import CrossEncoder
import pandas as pd

reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2",
    device=device
)

def rerank_similar_pitches(pitch, top_k=5, candidates=20):
    # First retrieve a broader set using the existing model
    initial = retrieve_similar_pitches(pitch, top_k=candidates)

    # Cross-Encoder jointly scores the pitch and each candidate
    pairs = [
        (pitch, row["pitch_text"])
        for _, row in initial.iterrows()
    ]

    scores = reranker.predict(pairs, show_progress_bar=False)

    initial = initial.copy()
    initial["reranker_score"] = scores

    return initial.sort_values(
        "reranker_score", ascending=False
    ).head(top_k).reset_index(drop=True)

test_pitch = """
We manufacture healthy millet-based snacks for urban consumers.
We plan to sell through our website, supermarkets and food distributors.
"""

reranked_results = rerank_similar_pitches(test_pitch, top_k=5)
display(
    reranked_results[
        ["startup_name", "industry", "source", "similarity", "reranker_score"]
    ]
)

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

,startup_name,industry,source,similarity,reranker_score
0,MilletAmma,Food and Beverage,Shark Tank India,0.6889,0.042453
1,TheCinnamonKitchen,Food and Beverage,Shark Tank India,0.5193,-0.329793
2,Let'sTry,Food and Beverage,Shark Tank India,0.5301,-1.509084
3,Madmix,Food and Beverage,Shark Tank India,0.5301,-1.509084
4,LilGoodness,Food and Beverage,Shark Tank India,0.5301,-1.509084

In [9]:

from transformers import pipeline
import torch

classifier_device = 0 if torch.cuda.is_available() else -1

industry_classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=classifier_device
)

INDUSTRIES = [
    "FoodTech and food products",
    "Healthcare and medical technology",
    "Financial technology and fintech",
    "Education technology",
    "Artificial intelligence and software",
    "E-commerce and retail",
    "Clean energy and sustainability",
    "Agriculture technology",
    "Consumer products and lifestyle",
    "Logistics and transportation"
]

def classify_industry(pitch):
    result = industry_classifier(
        pitch,
        candidate_labels=INDUSTRIES,
        multi_label=False
    )

    return pd.DataFrame({
        "industry": result["labels"],
        "confidence": result["scores"]
    })

display(classify_industry(test_pitch).head(5))

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

                          industry  confidence
0            E-commerce and retail    0.655077
1       FoodTech and food products    0.111565
2  Consumer products and lifestyle    0.072724
3  Clean energy and sustainability    0.064172
4           Agriculture technology    0.025247

In [10]:

from transformers import pipeline

sentiment_device = 0 if torch.cuda.is_available() else -1

finbert = pipeline(
    "text-classification",
    model="ProsusAI/finbert",
    device=sentiment_device
)

def analyze_news_sentiment(text):
    result = finbert(
        str(text)[:2000],
        truncation=True
    )[0]

    return {
        "sentiment": result["label"],
        "confidence": round(float(result["score"]), 4)
    }

print(analyze_news_sentiment(
    "Investors increase funding for promising food technology startups."
))

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

{'sentiment': 'positive', 'confidence': 0.924}

In [11]:

import feedparser
from urllib.parse import quote

def get_live_news(industry, max_results=5):
    query = quote(f"{industry} startup funding market")
    url = (
        "https://news.google.com/rss/search"
        f"?q={query}&hl=en-IN&gl=IN&ceid=IN:en"
    )

    feed = feedparser.parse(url)
    articles = []

    for entry in feed.entries[:max_results]:
        title = entry.get("title", "Untitled")
        sentiment = analyze_news_sentiment(title)

        articles.append({
            "title": title,
            "link": entry.get("link", ""),
            "published": entry.get("published", "Date unavailable"),
            "sentiment": sentiment["sentiment"],
            "sentiment_confidence": sentiment["confidence"]
        })

    return pd.DataFrame(articles)

display(get_live_news("FoodTech", max_results=5))

,title,link,published,sentiment,sentiment_confidence
0,Food Tech - 2026 Market & Investments Trends -...,https://news.google.com/rss/articles/CBMijAFBV...,"Fri, 02 Oct 2026 23:32:49 GMT",neutral,0.9372
1,Bezos Centre unveils Sustainable Food Accelera...,https://news.google.com/rss/articles/CBMi4wFBV...,"Wed, 22 Jul 2026 07:00:00 GMT",neutral,0.5186
2,Precision fermentation startup Verley raises $...,https://news.google.com/rss/articles/CBMixgFBV...,"Tue, 24 Feb 2026 08:00:00 GMT",positive,0.8822
3,"List of 46 Food Tech Startups in Vienna, Austr...",https://news.google.com/rss/articles/CBMisAFBV...,"Sun, 02 Aug 2026 07:00:00 GMT",neutral,0.9330
4,Those Vegan Cowboys Milks $7.3M in Funding to ...,https://news.google.com/rss/articles/CBMimwFBV...,"Thu, 18 Dec 2025 08:00:00 GMT",neutral,0.7951

In [12]:

def analyze_pitch(pitch, location="India"):
    industry_results = classify_industry(pitch)
    predicted_industry = industry_results.iloc[0]["industry"]

    similar = rerank_similar_pitches(
        pitch,
        top_k=5,
        candidates=20
    )

    news = get_live_news(predicted_industry, max_results=5)

    return {
        "predicted_industry": predicted_industry,
        "industry_scores": industry_results.head(5),
        "similar_startups": similar,
        "market_news": news,
        "location": location
    }

demo_pitch = """
Our startup produces affordable, healthy millet snacks for working
professionals. We sell online and want to expand into supermarkets
and local food distribution networks.
"""

analysis_result = analyze_pitch(demo_pitch, "Mumbai, India")

print("Predicted industry:", analysis_result["predicted_industry"])
print("\nTop similar startups:")
display(analysis_result["similar_startups"])
print("\nMarket news:")
display(analysis_result["market_news"])

Predicted industry: FoodTech and food products

Top similar startups:

,startup_name,industry,source,similarity,pitch_text,reranker_score
0,TheGreenSnack,Food and Beverage,Shark Tank India,0.5624,Healthy Snacks Online,-2.821541
1,Let'sTry,Food and Beverage,Shark Tank India,0.4608,Healthy Snacks,-3.549534
2,Madmix,Food and Beverage,Shark Tank India,0.4608,Healthy snacks,-3.549534
3,LilGoodness,Food and Beverage,Shark Tank India,0.4608,Healthy Snacks,-3.549534
4,TheCinnamonKitchen,Food and Beverage,Shark Tank India,0.4993,Plant-based healthy snacks,-3.790958

Market news:

,title,link,published,sentiment,sentiment_confidence
0,Agri-Food Tech Venture & Innovation Ecosystem ...,https://news.google.com/rss/articles/CBMioAFBV...,"Sat, 01 Aug 2026 07:00:00 GMT",neutral,0.8568
1,"List of 46 Food Tech Startups in Vienna, Austr...",https://news.google.com/rss/articles/CBMisAFBV...,"Sun, 02 Aug 2026 07:00:00 GMT",neutral,0.9330
2,Pegasus Tech Ventures and Ohayo Dairy Products...,https://news.google.com/rss/articles/CBMiwwFBV...,"Tue, 07 Jul 2026 07:00:00 GMT",neutral,0.7428
3,Top 10 Food Technology Trends Reshaping the US...,https://news.google.com/rss/articles/CBMifkFVX...,"Wed, 04 Mar 2026 08:00:00 GMT",neutral,0.5080
4,Precision fermentation startup Verley raises $...,https://news.google.com/rss/articles/CBMixgFBV...,"Tue, 24 Feb 2026 08:00:00 GMT",positive,0.8822

In [13]:

import gradio as gr
from urllib.parse import quote_plus
import pandas as pd

def make_pitch_report(pitch, location):
    result = analyze_pitch(pitch, location)

    industry = result["predicted_industry"]
    industry_scores = result["industry_scores"]
    similar = result["similar_startups"]
    news = result["market_news"]

    report = f"""
# 🚀 Startup Pitch Evaluation

## 1. Pitch overview

**Detected industry:** {industry}

**Location:** {location}

**Submitted pitch:**

{pitch}

## 2. Industry classification

"""
    for _, row in industry_scores.iterrows():
        report += (
            f"- **{row['industry']}** — "
            f"{row['confidence']:.1%} model confidence\n"
        )

    report += "\n## 3. Similar startup pitches\n\n"

    for _, row in similar.iterrows():
        report += (
            f"### {row['startup_name']}\n"
            f"- Industry: {row['industry']}\n"
            f"- Source: {row['source']}\n"
            f"- Semantic similarity: {row['similarity']:.3f}\n"
            f"- Reranker score: {row['reranker_score']:.3f}\n"
            f"- Description: {str(row['pitch_text'])[:350]}\n\n"
        )

    report += "## 4. Industry news and sentiment\n\n"

    if news.empty:
        report += "No news articles were returned. Try again later.\n"
    else:
        for _, row in news.iterrows():
            report += (
                f"- [{row['title']}]({row['link']})\n"
                f"  - Published: {row['published']}\n"
                f"  - FinBERT sentiment: **{row['sentiment']}** "
                f"(confidence: {row['sentiment_confidence']:.2f})\n\n"
            )

    supplier_query = quote_plus(
        f"{industry} suppliers distributors {location}"
    )
    market_query = quote_plus(
        f"{industry} market competitors {location}"
    )
    funding_query = quote_plus(
        f"{industry} startup funding investors India"
    )
    map_query = quote_plus(
        f"{industry} suppliers distributors near {location}"
    )

    report += f"""
## 5. Business research links

These are search links to help you research opportunities. They are
not verified supplier recommendations.

- [Find suppliers and distributors](https://www.google.com/search?q={supplier_query})
- [Research competitors and the market](https://www.google.com/search?q={market_query})
- [Find startup investors and funding information](https://www.google.com/search?q={funding_query})
- [Locate relevant businesses on Google Maps](https://www.google.com/maps/search/{map_query})

## 6. Preliminary recommendations

- Validate demand with potential customers before scaling.
- Compare competitor pricing, distribution channels and product differentiation.
- Prepare realistic unit economics, gross margins and customer acquisition costs.
- Verify supplier credentials, product quality and delivery terms independently.

**Important:** Similarity, industry confidence and news sentiment are model outputs.
They do not establish business viability or guarantee investment.
"""

    return report, result


def run_pitch_analysis(pitch, location):
    if not pitch or not pitch.strip():
        return "Please enter a startup pitch.", None, "", location

    try:
        report, result = make_pitch_report(pitch.strip(), location.strip() or "India")
        return report, result, pitch, location
    except Exception as e:
        return f"Analysis failed: {type(e).__name__}: {e}", None, pitch, location

In [14]:

def pitch_chat(message, history, analysis, pitch, location):
    if not message or not message.strip():
        return "Ask me something about your startup pitch."

    if not analysis:
        return "Please submit a pitch using **Analyze My Pitch** first."

    q = message.lower()
    industry = analysis["predicted_industry"]
    similar = analysis["similar_startups"]
    news = analysis["market_news"]

    if any(word in q for word in ["industry", "sector", "category"]):
        scores = analysis["industry_scores"]
        lines = [
            f"Your pitch is most closely classified as **{industry}**.",
            "",
            "Other industry scores:"
        ]
        for _, row in scores.head(5).iterrows():
            lines.append(
                f"- {row['industry']}: {row['confidence']:.1%}"
            )
        return "\n".join(lines)

    if any(word in q for word in [
        "similar", "competitor", "competition", "startup"
    ]):
        lines = ["Here are the closest retrieved startup pitches:", ""]
        for _, row in similar.head(5).iterrows():
            lines.append(
                f"- **{row['startup_name']}** "
                f"({row['industry']}; {row['source']}) — "
                f"similarity {row['similarity']:.3f}"
            )
        lines += [
            "",
            "These are similarity matches, not necessarily direct competitors."
        ]
        return "\n".join(lines)

    if any(word in q for word in ["news", "market", "sentiment", "trend"]):
        if news.empty:
            return "No news was retrieved. Please retry the analysis later."

        lines = ["Recent retrieved industry headlines:", ""]
        for _, row in news.head(5).iterrows():
            lines.append(
                f"- [{row['title']}]({row['link']}) — "
                f"{row['sentiment']} sentiment "
                f"(confidence {row['sentiment_confidence']:.2f})"
            )
        lines += [
            "",
            "Sentiment is inferred from headlines and may not reflect the full article."
        ]
        return "\n".join(lines)

    if any(word in q for word in [
        "supplier", "distributor", "vendor", "location", "where"
    ]):
        query = quote_plus(f"{industry} suppliers distributors {location}")
        maps = quote_plus(f"{industry} suppliers near {location}")
        return (
            f"For your **{industry}** pitch, start researching suppliers "
            f"and distributors around **{location}**.\n\n"
            f"- [Search suppliers and distributors](https://www.google.com/search?q={query})\n"
            f"- [Search nearby businesses on Maps](https://www.google.com/maps/search/{maps})\n\n"
            "These are research links, not verified supplier listings."
        )

    if any(word in q for word in [
        "improve", "feedback", "weakness", "recommend", "advice", "score"
    ]):
        return (
            f"Your pitch is classified as **{industry}**. To strengthen it, "
            "explain the customer problem, target market, unique advantage, "
            "pricing, competitors, distribution strategy and evidence of demand. "
            "Include revenue, costs, gross margin and funding requirements where "
            "available. I cannot give a reliable investment score without "
            "validated financial and market evidence."
        )

    return (
        f"Your current pitch analysis focuses on **{industry}**.\n\n"
        "Try asking me about:\n"
        "- Industry classification\n"
        "- Similar startups and competitors\n"
        "- Live market news and sentiment\n"
        "- Suppliers and distributors near your location\n"
        "- Ways to improve your pitch"
    )

In [15]:

with gr.Blocks(title="Startup Pitch Evaluator AI") as app:
    gr.Markdown(
        """
        # 🚀 Startup Pitch Evaluator AI
        ### Deep-learning-powered startup research assistant

        Enter your business idea to classify its industry, find similar
        startup pitches, examine market headlines and explore business links.
        """
    )

    pitch_input = gr.Textbox(
        label="Describe your startup pitch",
        placeholder=(
            "Example: We produce affordable millet snacks for urban "
            "consumers and sell through online platforms and supermarkets."
        ),
        lines=5
    )

    location_input = gr.Textbox(
        label="Target location",
        value="Mumbai, India"
    )

    analyze_button = gr.Button("Analyze My Pitch", variant="primary")
    report_output = gr.Markdown()

    analysis_state = gr.State(None)
    pitch_state = gr.State("")
    location_state = gr.State("India")

    analyze_button.click(
        fn=run_pitch_analysis,
        inputs=[pitch_input, location_input],
        outputs=[
            report_output,
            analysis_state,
            pitch_state,
            location_state
        ]
    )

    gr.Markdown("---")
    gr.Markdown("## 💬 Ask questions about your pitch")

    gr.ChatInterface(
        fn=pitch_chat,
        additional_inputs=[
            analysis_state,
            pitch_state,
            location_state
        ],
        title="Entrepreneur Assistant",
        description=(
            "Analyze your pitch first, then ask about competitors, "
            "industry trends, news or suppliers."
        )
    )

app.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://83eb182da58e6f4310.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)